# Taken from roblox-ts under the MIT license https://github.com/roblox-ts/roblox-ts/blob/master/.github/workflows/ci.yml

name: CI

on:
  pull_request:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Install Foreman
        uses: rojo-rbx/setup-foreman@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Selene
        run: selene lib
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Run StyLua check
        uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check lib
  unit-tests:
    name: Unit Tests
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Install Roblox Studio
        uses: OrbitalOwen/roblox-win-installer-action@1.1
        with:
          # This cookie is intentionally public, because secrets are not available in pull request CI runs
          # It is from an empty account and not a security vulnerability
          cookie: ${{ secrets.ROBLOSECURITY || '_|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items.|_C70AE2E0C6251717CC5D404C22C3037A4939940614D8D1A8536320B88EF78EDC145998EC5333FB7F5E09005B1E0A37B21278246C16AE1CE79E1A96C3ACEE26C33C0FB9B3628F0A90387E65322E55439EB6C75DD5A66F640F21FF31E47C40800B5E601CC7BDA1D0E33F2FEC3380FD4C29380528A9A4BB5DBAC3A3289C39E49D0C1952807FEBCB01E600F76945E0B1998979C50DCF0A56AB14EF17974C1E38F52ECA31DE5B820250327D03D6658E85FA3D7717484311FC7D6E6450D1FE5688CE7A7F942342BCC8767A7305F0EA31AA52C3DE9E8A3DB0885EE37F71149830A597CB21ECBF1CA2FA022443DC6F34EB0BFBF765801F7689D43749B1E3FD120EDBA1D2B1202597B6B9844076F6EF529D53D062D05EAF386398F2EA58CBBCE78E269BF1231C25F6C159AA3C609F169D0CAE7F628C1C33C30CD333C56E1551571412120FEB0258D2E91EA62A006C1C24E3082662A15B91DA57E33E5C8A70669D7C98B7746E9C345C46CB997439C77A94D1F89F68B1A13684' }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Foreman
        uses: rojo-rbx/setup-foreman@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build test place
        run: rojo build test.project.json -o test.rbxl

      - name: Run tests
        shell: bash
        run: run-in-roblox --place test.rbxl --script tests.server.lua > test-out.txt
        continue-on-error: true

      - name: Check test status
        shell: bash
        run: cat test-out.txt | grep "0 failed, 0 skipped" || (cat test-out.txt && exit 1)
